// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: archnets_dispatcher_config.proto

package dispatcher

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionConfig) Reset() {
	*x = SessionConfig{}
	mi := &file_archnets_dispatcher_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfig) ProtoMessage() {}

func (x *SessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_archnets_dispatcher_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfig.ProtoReflect.Descriptor instead.
func (*SessionConfig) Descriptor() ([]byte, []int) {
	return file_archnets_dispatcher_config_proto_rawDescGZIP(), []int{0}
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *SessionConfig         `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_archnets_dispatcher_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_archnets_dispatcher_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_archnets_dispatcher_config_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetSettings() *SessionConfig {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_archnets_dispatcher_config_proto protoreflect.FileDescriptor

const file_archnets_dispatcher_config_proto_rawDesc = "" +
	"\n" +
	" archnets_dispatcher_config.proto\x12\x1carchnets.core.app.dispatcher\"\x15\n" +
	"\rSessionConfigJ\x04\b\x01\x10\x02\"Q\n" +
	"\x06Config\x12G\n" +
	"\bsettings\x18\x01 \x01(\v2+.archnets.core.app.dispatcher.SessionConfigR\bsettingsBq\n" +
	" com.archnets.core.app.dispatcherP\x01Z,github.com/archnets/node/core/app/dispatcher\xaa\x02\x1carchnets.core.app.dispatcherb\x06proto3"

var (
	file_archnets_dispatcher_config_proto_rawDescOnce sync.Once
	file_archnets_dispatcher_config_proto_rawDescData []byte
)

func file_archnets_dispatcher_config_proto_rawDescGZIP() []byte {
	file_archnets_dispatcher_config_proto_rawDescOnce.Do(func() {
		file_archnets_dispatcher_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_archnets_dispatcher_config_proto_rawDesc), len(file_archnets_dispatcher_config_proto_rawDesc)))
	})
	return file_archnets_dispatcher_config_proto_rawDescData
}

var file_archnets_dispatcher_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_archnets_dispatcher_config_proto_goTypes = []any{
	(*SessionConfig)(nil), // 0: archnets.core.app.dispatcher.SessionConfig
	(*Config)(nil),        // 1: archnets.core.app.dispatcher.Config
}
var file_archnets_dispatcher_config_proto_depIdxs = []int32{
	0, // 0: archnets.core.app.dispatcher.Config.settings:type_name -> archnets.core.app.dispatcher.SessionConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_archnets_dispatcher_config_proto_init() }
func file_archnets_dispatcher_config_proto_init() {
	if File_archnets_dispatcher_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_archnets_dispatcher_config_proto_rawDesc), len(file_archnets_dispatcher_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_archnets_dispatcher_config_proto_goTypes,
		DependencyIndexes: file_archnets_dispatcher_config_proto_depIdxs,
		MessageInfos:      file_archnets_dispatcher_config_proto_msgTypes,
	}.Build()
	File_archnets_dispatcher_config_proto = out.File
	file_archnets_dispatcher_config_proto_goTypes = nil
	file_archnets_dispatcher_config_proto_depIdxs = nil
}
